server.port: 7100
#eureka client配置
eureka.client.serviceUrl.defaultZone: http://admin:prolog00212@192.168.0.167:8761/eureka/

spring:
  #redis配置
  redis: 
    host: 192.168.0.6
    port: 6379
    password: prolog0212
    database: 4

  #链路跟踪
  zipkin:
    base-url: http://192.168.10.167:9411
  sleuth:
    enable: false
    sampler:
      probability: 0.5

  devtools: 
    restart: 
      enabled: true
  datasource: 
    driverClassName: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@192.168.0.8:1521:cloudpltfm
    username: CLOUDPLTM_TEST
    password: CLOUDPLTM_TEST
    initialSize: 0 #初始化大小
    minIdle: 5 #最小空閒
    maxActive: 50 #最大連接數
    maxWait: 60000 #最大等待時間
    minEvictableIdleTimeMillis: 25200000 #最小生存時間
    
