#eureka client配置
eureka: 
  instance: 
    # 注册时使用ip而不是主机名
    preferIpAddress: true
    instanceId: ${server.ipAddress}:${spring.application.name}:${server.port}:@project.version@
    health-check-url-path: /actuator/health
    # 状态地址为api地址
    statusPageUrlPath: /${server.servlet.contextpath:}/apidoc.html
    leaseRenewalIntervalInSeconds: 20 #租期更新时间间隔（默认30秒）
    leaseExpirationDurationInSeconds: 60 #租期到期时间（默认90秒）

  
server:
  ipAddress: 127.0.0.1
  port: 7100
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB

#springboot admin配置   
management.endpoints.web.exposure.include: "*"
        
spring:
  application.name: prolog-oa
  profiles.active: prd

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 240000

ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 2
feign:
  hystrix:
    enabled: true
prolog: 
  jwt.tokenHead: Bearer
  #api文档配置文件
  apidoc:
    title: 普罗格工时系统
    basePackage: com.prolog.time.management
    description: 普罗格工时系统
    version: 1.0
  dao: 
    dialect: oracle
    pagehelper: #pagehelper分页插件配置
      helperDialect: ${prolog.dao.dialect}
      reasonable: true
      supportMethodsArguments: true
      pageSizeZero: false
      params: count=countSql
    #公共配置与profiles选择无关 mapperLocations指的路径是src/main/resources
    mybatis:
      typeAliasesPackage: #mode包位置
      mapperLocations: classpath:mapper/*.xml
      configuration:
        call-setters-on-nulls: true
  ms: 
    clientId: prologoa
    clientSecret: prologoa
    oauthServer: api-gateway/service-authorization #192.168.10.167:8100



